### ISSUE TITLE
Select all (automatically) the new page url

### ISSUE THREAD

**Issue by DezinoGraphist** [jimschubert/NewTab-Redirect#105]
Thanks for this extremely helpful extension. Though I'm pretty much satisfied except for one feature. Every time I open a new tab I have to press Command+A (Ctrl+A) before typing the web address. This is a small but annoying extra effort. Request you to pls add an additional feature in your 'Always update tab' so that the new page url automatically gets selected.
Look forward to your prompt support.
Best

**Comment by jimschubert** [comment]
Hi, please refer to #50 for full discussion on this topic.

In short, extensions have no control over this and the 'always update tab' refers to how the extension executes the redirect only. Sorry, but it's a limit of the browser and extension API.
