### ISSUE TITLE
Request: Select URL in address bar (when it's about:blank)

### ISSUE THREAD

**Issue by quape** [jimschubert/NewTab-Redirect#108]
Hi there, I'm using about:blank for a new tab because I just want a clean page. So, when opening a new tab the address bar is focussed and I can start typing a new URL. But I have to do Cmd-A + Backspace first to clean the field first. It would be nice if the old URL (in my case about:blank) was all selected so one can just start typing.

**Comment by jimschubert** [comment]
Thanks for the request. Unfortunately, Chrome handles the highlight of this address bar inconsistently across versions. See issue #50 for further discussion. I'm closing this issue so there is a single open issue for this.

**Comment by quape** [comment]
Though it works know :)
