### ISSUE TITLE
Google Chrome Themes

### ISSUE THREAD

**Issue by SamStace** [jimschubert/NewTab-Redirect#111]
Are google chrome themes compatible with this extension? My themes don't seem to work when i have the NewTab-Redirect extension enabled.

**Comment by jimschubert** [comment]
As far as I know, extensions can't access Themes. I recall reading on Google Code where a Chrome developer claimed this limitation was for security reasons, but I can't seem to find the link.

**Comment by SamStace** [comment]
Thank you for answering my question!

- Samuel

**Comment by Walkman100** [comment]
See #57, which also has two linked issues

**Comment by jimschubert** [comment]
Closing, question is answered.
