### ISSUE TITLE
Don't focus address bar after opening a new local site

### ISSUE THREAD

**Issue by dsdshcym** [jimschubert/NewTab-Redirect#112]
Well. I know this may sounds wired. 
Because normally chrome will not automatically focus address bar when open a
normal website, and most people want it to be focused.

Here is my problem:
- I use cVim

  - I don't want to use address bar, since I can open a tab using cVim commands
    or shortcuts
  - And I also use presentation mode to get a fullscreen experience

- I want to keep chrome open

  - So I use this extension and another extension named `Last Tab` to open an
    empty tab
    (chrome-extension://ihlenndgcmojhcghmfjfneahoeklbjjh/pages/blank.html) ,
    provided by cVim, every time I close the last tab.
  - But I don't want to auto focus address bar everytime it's opened
  - As far as I tested, chrome will always auto focus address bar when open a
    local file

It's okay if there is no solution for this, since it's a super personal need.

**Comment by Walkman100** [comment]
#46 and #50

**Comment by dsdshcym** [comment]
@Walkman100 Sorry I didn't read these issues carefully. 

Thank you! I'll close this issue.

**Comment by jimschubert** [comment]
@Walkman100 thanks for the links.

@dsdshcym sorry for not responding earlier. Github keeps removing my email notification preferences.
