### ISSUE TITLE
Omnibar focus

### ISSUE THREAD

**Issue by inexist3nce** [jimschubert/NewTab-Redirect#113]
As explained in [the wiki](https://github.com/jimschubert/NewTab-Redirect/wiki#why-doesnt-the-url-bar-focus-), the omnibar loses focus because of the page redirection. This could be fixed by avoiding it completely and using an iframe covering the entire page. (Or maybe by not having a ton of javascript in `main.html`, redirecting the user as fast as possible)

**Comment by inexist3nce** [comment]
I just created my own extension and iframes work. The omnibar doesn't lose focus.

**Comment by jimschubert** [comment]
@inexist3nce you lose a lot of web functionality by embedding the page in iframes. You also open yourself to cross site scripting and other security issues because, now, sites will all have access to a "super-site" (your extension page). There's also HTML5 features that won't work in an iframe like this.

**Comment by dbkaplun** [comment]
@jimschubert using an iframe as a redirect mechanism seems fine to me. You're right that iframes are not perfect and may cause headaches, but as far as security, most people won't assign a malicious site to their new tab page, and if they do it's on them. I think a warning like "using this redirect mechanism is potentially insecure" would be reasonable. For the vast majority of users (myself included) I would say losing omnibar focus is a much bigger problem.

@inexist3nce PR #123 implements iframes as a redirection mechanism, works great for me!

**Comment by jimschubert** [comment]
I'm not willing to tell over half a million users "I guess you should have understood web technology." Nor am I willing to deal with the onslaught of complaints due to such a feature (I already receive enough "how dare you install this software without my knowledge emails.").

**Comment by dbkaplun** [comment]
@jimschubert I've updated the PR. I think it will solve this particular problem cleanly, as well as being clear about possible security risk. Let me know if it needs changing :smile:
