### ISSUE TITLE
redirect is too slow and overwrites existing URLs as a result

### ISSUE THREAD

**Issue by modelm** [jimschubert/NewTab-Redirect#114]
I wanted a blank new tab page, so I installed this extension and set my new tab page to "about:blank".

I have noticed that frequently I have a URL in my clipboard when opening a new tab, and I hit cmd-t followed by cmd-v followed by enter in rapid succession. Then I watch as the extension kicks in and overwrites the URL I've just entered with "about:blank" and loads the empty page.

I have to re-focus the address bar and re-enter the URL at this point to get where I was initially trying to go.

It would be great if the delay could be removed entirely, or failing that if the extension could somehow recognize that there is already a URL in the address bar and not act in that case.

**Comment by Hrxn** [comment]
I'm not sure if this helps, but you should be able to do something like this 
```
{
  "name": "My extension",
  ...

  "chrome_url_overrides" : {
    "newtab": "myPage.html"
  },
  ...
}
```

In an extension manifest file.

That would be some sort of 'static redirection', if you will

Source:
https://developer.chrome.com/extensions/override

**Comment by modelm** [comment]
For anybody else who has this issue, I found another extension that does the job:

https://chrome.google.com/webstore/detail/empty-new-tab-page/dpjamkmjmigaoobjbekmfgabipmfilij/related

**Comment by dbkaplun** [comment]
+1

@Hrxn looks like it's already using this API: https://github.com/jimschubert/NewTab-Redirect/blob/7089a1c8b3dba8b25e00abd97da58fa201f7f246/manifest.json#L13

**Comment by dbkaplun** [comment]
One possible solution is to use an <iframe> to implement a "redirect" without changing the URL bar: #122

**Comment by jimschubert** [comment]
@modelm there's no way to remove the redirection delay completely, the whole point of the extension is to enable non-technical users to easily specify a dynamic URL.

I have an example of an extension which redirects to the built in apps page, https://github.com/jimschubert/chrome-apps-newtab. The API for tabs requires updating in one way for web links and a different way for built-in chrome links. I hope this helps.

Sorry for the delay in response. I have apparently lost notifications for github issues.

**Comment by Walkman100** [comment]
Another thing you can do is use the NTR "apps" page and disable all permissions, then you get a pretty blank page that doesn't redirect, allowing you to open a new tab and paste a url in without without waiting.

**Comment by joeparkerz** [comment]
How can that be done?

**Comment by Walkman100** [comment]
Remove the URL to redirect to and disable all permissions. I use Vivaldi now, which allows me to set New Tab page settings, so I can't guide you through the exact steps sorry.

**Comment by joeparkerz** [comment]
Oh nice.. Another approach is to block these urls through ublock.

https://www.google.com/_/chrome/newtab?espv=2&ie=UTF-8
https://www.google.com/_/chrome/newtab-serviceworker.js

**Comment by joeparkerz** [comment]
Well this won't work.

{
  "name": "Test Tab",
  "description": "",
  "version": "0.1",
  "manifest_version": 2,
  "optional_permissions": [],
  "permissions": [""],
  "chrome_url_overrides": {
    "newtab": ""
  }
}

**Comment by Walkman100** [comment]
If you want a blank new tab page, download https://github.com/jimschubert/chrome-apps-newtab and change the line in `manifest.json` to:
```json
"chrome_url_overrides": { "newtab": "about:blank" },
```

**Comment by joeparkerz** [comment]
Are you sure? I get error File not found: about:blank.

**Comment by jimschubert** [comment]
`"about:blank"` isn't a valid file for the newtab target. It has to be a file local to the extension or http/https. Joe's changes may be the only good solution to a blank new tab page which also highlights the address bar.
