### ISSUE TITLE
Why start-up page always shows 2 tabs, one of which is from my previous browsing history?

### ISSUE THREAD

**Issue by shuanglu127** [jimschubert/NewTab-Redirect#118]
I like this "NewTab-Redirect" app, very fast and convenient. However, 2 Questions:

a. Why always 2 start-up tabs? Can't I configure it to show only one pre-specified page?
b. This is more important than above: The 1st tab showing up after starting up is always whatever I was browsing before. Is there any way to turn this off, or redirect it to a blank page? (Ideally I only want to show one blank page after starting-up.)

Thank you!

**Comment by jimschubert** [comment]
@shuanglu127 this extension has nothing to do with browser startup. The extension only modifies the page displayed when you create a new tab. If this is happening when you start the browser, you probably have some setting causing this or some other extension affecting this. Unfortunately, that's far outside the details of the extension that I'm able to assist with.
