### ISSUE TITLE
Is it possible to redirect to an already opened tab?

### ISSUE THREAD

**Issue by balzss** [jimschubert/NewTab-Redirect#120]

**Comment by jimschubert** [comment]
@balzss this would be far too complex for this extension to attempt.  You would have to iterate all open windows and tabs to get the target tab. You could make logic to open the last tab, but that logic would add more delay into the redirection of this extension. If you wanted anything more than the last tab, you'd need a selection page out dialog.

You can achieve this pretty easily with Vimium. If you haven't used it before, you should check it out.
