### ISSUE TITLE
Clear address bar [feature_request]

### ISSUE THREAD

**Issue by selivan** [jimschubert/NewTab-Redirect#130]
It may be nice to make option to have in new tab clear address bar without text and with cursor in it. For me that would be better than pre-selected text of redirect page, that we have now.

**Comment by dbkaplun** [comment]
There is a PR (#123) open for redirecting using iframes to keep the omnibox empty. See also: #129

**Comment by selivan** [comment]
Should I close this one as duplicate?

**Comment by jimschubert** [comment]
You can if you'd like.

**Comment by selivan** [comment]
closed - duplicate
