### ISSUE TITLE
Theme doesn't work

### ISSUE THREAD

**Issue by smcclure99** [jimschubert/NewTab-Redirect#131]
Love the tab redirect but when I tried to use a theme and your tab redirect the theme doesn't work :(

**Comment by techadict** [comment]
There must be a conflict with the specific theme and the redirect tabs extension. Try using another theme and see if it works better

**Comment by jimschubert** [comment]
Chrome doesn't give theme​ access to extensions. It's considered a security risk for whatever reason (possibly because it requires relaxing extension constraints).

Sorry.
