### ISSUE TITLE
Redirect doesn't work on Chrome for Linux

### ISSUE THREAD

**Issue by weaverba137** [jimschubert/NewTab-Redirect#132]
New Tab Redirect does not work on my Linux/Chrome system.  It does work on my MacOS/Chrome system.  Specifically, the URL that I have configured doesn't open up on opening a new tab.  Instead I see the default New Tab Redirect page, with links to several Google Apps.  The exact same URL works fine on MacOS/Chrome.

System details:
Ubuntu Linux 14.04, kernel 4.4.0
Chrome version: 54.0.2840.100 (64-bit)

**Comment by camellirite** [comment]
Can you show how to replicate the issue? Chrome on Linux too and its working perfectly fine for me. It might be the link

**Comment by jimschubert** [comment]
Sorry, I don't know why I only received notification for the most recent comment. 

A lot of things can cause this: 

* Having more than one redirect extension installed 
* (When sync is enabled) Being logged into a Google account with a saved URL that overwrites your local setting on sync 
* If Chrome has an outstanding update which affects the newtab override API, it'll sometimes silently unload extensions

None of those are within my control with the extension.

However, the Linux version of Chrome sometimes has differences that cause problems. I was relieved when I switched to Mac as my main OS. You could inspect the extensions background page and see if there are any errors in the dev console.

With a repro step, I could check it out. You can email me if you'd like to keep the URL private.

**Comment by weaverba137** [comment]
After playing around with this a bit more, I think this may have been a problem with http versus https.  The URL I had saved was http, but the destination was redirecting it to https.  When I explicitly saved the URL as https, the problem went away.

**Comment by jimschubert** [comment]
That's really weird behavior. If tab.update in Chrome's API is so broken that is not following redirects, its probably worth raising the issue on Chrome's bug tracker.

I'll test locally and post to the tracker, unless you have a clear repro and are comfortable doing it.

**Comment by weaverba137** [comment]
I don't think I'm sufficiently familiar with that.

**Comment by jimschubert** [comment]
Cool. I'll do it when I get a chance. Thanks for following up with the HTTPS info.
