### ISSUE TITLE
Unable to activate or remove

### ISSUE THREAD

**Issue by cboudard** [jimschubert/NewTab-Redirect#134]
NewTab-Redirect is installed on my Chrome (Version 55.0.2883.87 m (64-bit)) on Windows 7. But each time I am trying to enable it or remove it, Chrome is crashing. When I am trying to reinstall it, Chrome is also crashing. What should I do?

**Comment by jimschubert** [comment]
I'm not sure why Chrome would crash. This isn't something that extensions have control over, unfortunately. I'd recommend submitting a support request directly to Google (Feedback/Help in the options menu).

If this was happening on my machine, I would look for other extensions that override the new tab page and temporarily disable those to see if it helps. If that doesn't  help, you could close Chrome and manually delete the folder for the extension (location is documented on the wiki, your version folder will be different though: https://github.com/jimschubert/NewTab-Redirect/wiki#how-do-i-edit-the-extensions-source-locally-).

**Comment by jimschubert** [comment]
Haven't received a response, so I'm closing this. please reopen if needed.
