### ISSUE TITLE
I'd like to be able to change the <title /> of the redirect page

### ISSUE THREAD

**Issue by lyramsr** [jimschubert/NewTab-Redirect#136]
My new tab page is called "New tab", and I'd prefer it if the redirect page's title were consistent with that. It would make the transition a little more seamless.

**Comment by jimschubert** [comment]
I'm not sure I understand. The New Tab page doesn't know details of your target URL, and doesn't exist in memory after the redirect is initiated.

Would you prefer instructions for a very simplified new tab override extension and see if that suits your needs?

**Comment by wolflambert** [comment]
I don't think I explained this thoroughly enough. The point is that the extension replaces the new tab page with an internal page that tells the browser to redirect the page to [user-defined URL]. You probably put a meta redirect on the page, or something similar, to achieve this. _That_ page's title is defined in the HTML as "New Tab Redirect".

What this means is that for a split second, the tab says "New Tab Redirect", right before it redirects. This is what I'd like to be able to change.

**Comment by jimschubert** [comment]
@wolflambert I got ya. Unfortunately, changing this or even removing it could be a violation of Chrome rules for extensions, which are pretty strict about displaying information to users when an extension has control.

**Comment by jimschubert** [comment]
I haven't heard back, so I'm assuming my last comment answered concerns.
