### ISSUE TITLE
Focus in URL

### ISSUE THREAD

**Issue by luckyguy73** [jimschubert/NewTab-Redirect#137]
right now the focus goes to the google search input when the page loads which makes perfect sense, but it would be really great if i could have the option to move the focus to the URL as many times i am opening a new tab just to open a page i know the site name and start typing, but alas the cursor goes to the google search box so i am now searching for the site instead of going to the site.

**Comment by jimschubert** [comment]
Closing as a duplicate of #50, which is not functionality that can be controlled by e extension developers.
