### ISSUE TITLE
Failed to load resource: net::ERR_FAILED

### ISSUE THREAD

**Issue by riramar** [jimschubert/NewTab-Redirect#139]
After removing the NewTab extension I'm seeing the errors below on console for every new chrome tab opened.

newtab:7 SW registered
redirect.html Failed to load resource: net::ERR_FAILED

**Comment by jimschubert** [comment]
Sorry I missed this issue. Seems like you needed to restart the browser. This includes any status bar icons. Once Chrome is fully released from memory, it will no longer hold references to removed extensions.
