### ISSUE TITLE
Mark complete URL in new tab

### ISSUE THREAD

**Issue by Keridos** [jimschubert/NewTab-Redirect#142]
As the title says, add an option to mark the whole URL when opening a new tab, thus pressing anything will automatically overwrite the url instead of writing in front of it.

**Comment by ilozka** [comment]
This is a very annoying bug - it worked well before Chrome 60 (or extension update got with Chrome 60?).

**Comment by jacekkopecky** [comment]
Hi, this has been discussed in #140 . 
It seems to be impossible to fix this in the NewTab-Redirect extension; see how I worked around the problem at https://gist.github.com/jacekkopecky/410872d6fee9b7632e7a5cafade4f199

**Comment by Keridos** [comment]
Wouldn't it be possible to simply let the address bar free?

**Comment by jimschubert** [comment]
Extensions don't have control over the address bar.

This is a symptom of how the browser focuses pages.  Chrome sometimes highlights the address bar, and sometimes doesn't. The extension options offer one possible solution that has worked for some, but there's no other workaround from the extension level.

**Comment by Keridos** [comment]
Yeah probably may need to make an issue on that upstream.

**Comment by jimschubert** [comment]
It's not something that can be fixed upstream. Allowing extensions access to the "chrome" presents a huge security risk. Giving access to the address bar would also mean giving access to what users type or visit, including basic authentication passwords included in URLs and other things you don't want developers having. Granted, the tabs permission and possibly the history permission could expose these as well, but they can't initiate navigation. Only new tab pages or explicitly clicking on links can, and this is why you get a warning when installing a new tab override extension.

Even if it was possible upstream, there are a lot of threading complexities to such behavior. It would be worth the effort and security risk.

**Comment by jimschubert** [comment]
Apparently, there's a bug for chrome which attempts to fix this behavior. https://bugs.chromium.org/p/chromium/issues/detail?id=752794

In my previous experience (this extension was created in 2009), this behavior has existed in and off between builds and was often different between operating systems.

While I'm hopeful the Chrome bug fixes this in Chrome 62, my hopes aren't that high.

I'm closing this as it's related to many other issues reported on this extension and having too many open pages down the parent card #50.
