### ISSUE TITLE
chrome://apps on new tab doesn't take the focus on Chrome 61

### ISSUE THREAD

**Issue by sysqo82** [jimschubert/NewTab-Redirect#143]
When setting chrome://apps/ as the new tab redirect on Chrome 61.0.3163.91 (Official Build) (64-bit)
The URL doesn't get highlighted and when starting to type, the text is added to the beginning of "chrome://apps/"
![2017-09-20_1448](https://user-images.githubusercontent.com/20111075/30647168-d7d81f32-9e12-11e7-944a-6b89d37527aa.png)
![2017-09-20_1448v](https://user-images.githubusercontent.com/20111075/30647169-d7d9c9c2-9e12-11e7-9719-44b4f446bf32.png)

**Comment by dopearmy** [comment]
The same thing happens to me. 
I'm using Chromium Version 61.0.3163.91 (Developer Build) (64-bit).

**Comment by barmar** [comment]
It's not specific to the URL. I have about:blank as my new tab URL, and the same problem happens since upgrading to Chrome 61 today.

**Comment by jimschubert** [comment]
This is a bug in Chrome. https://bugs.chromium.org/p/chromium/issues/detail?id=752794

closing as this is not something that new tab extensions have control over.
