### ISSUE TITLE
URL in address bar not selected

### ISSUE THREAD

**Issue by danielegrattarola** [jimschubert/NewTab-Redirect#144]
Hi, 
when I open a new tab, the text in the address bar is not selected anymore (started noticing this since the Chrome update to v61).
I'm on Ubuntu 16.04 64 bit, you can reporduce the behiavior by setting the redirect URL to any URL (local or online). 
I've noticed that other people, too, have this problem. Is there something we can do to fix it?

Thanks, 
Daniele

**Comment by esreverse** [comment]
Same in Mac OS. Very cumbersome to always select the whole URL before being able to enter something new.

**Comment by jimschubert** [comment]
This is a bug in Chrome, and isn't fixable from APIs available to extensions.

It's supposedly fixed in the Canary build (v62), however that behavior was always iffy and I'd be surprised if it becomes stable in v62.

**Comment by danielegrattarola** [comment]
Let's hope they fix it, it's super annoying. 
Thanks anyway!

**Comment by linuxlurak** [comment]
Happens to me too since some days... This chrome bug is very annoying indeed. Would it be a temporary solution to place the cursor and then (or before) clear the edit box? Cheers!

**Comment by jimschubert** [comment]
Extensions have no access to the browser's interface. There's nothing that can be done on my end.

**Comment by cjauvin** [comment]
I agree with the others, this is a very annoying change of behavior (although I understand nothing can probably be done): I was used to Ctrl+T and start typing my google search query right away.. which doesn't work anymore.. Guess it's time to retrain my muscle memory!

**Comment by jimschubert** [comment]
To highlight the address bar:

Windows:
Ctrl + l or Alt + d or F6
L for Location, D for Destination

Mac:
⌘ + l
L for Location

**Comment by danielegrattarola** [comment]
I'm thinking of remapping a shortcut to Ctrl+T > Ctrl+L JUST for this.

**Comment by jimschubert** [comment]
@danielegrattarola I don't use Windows, is this difficult to do (like per user level)?

**Comment by danielegrattarola** [comment]
I use Ubuntu and I haven't really used Windows 10 much, but I think that software like AutoHotkey could be helpful for this purpose under Windows. 
Also, since we're on the subject, on Ubuntu you could use xdotool and the default shortcut editor.
I don't know about Mac, but IIRC BetterTouchTool has a shortcut editor.

**Comment by JBtje** [comment]
this "issue" is solved in Chrome 63.0.3226.0, which is a canary version
https://www.google.com/chrome/browser/canary.html

**Comment by stenrap** [comment]
If you were using this with `about:blank` like I was, you can do an empty URL instead. New tabs show the extension's options page, but at least the URL doesn't have to be selected.

**Comment by godey4me** [comment]
@stenrap How do you get the empty url after setting `about:blank` as the redirect url?
Thanks

**Comment by stenrap** [comment]
@godey4me: I _was_ using `about:blank` but now I'm using an empty URL in the options, which results in an empty URL when I open a new tab:

![empty](https://user-images.githubusercontent.com/1420644/31250604-8c24cf6e-a9d8-11e7-9f3e-5018e3d68206.png)

**Comment by godey4me** [comment]
aahh i see. Better than having to erase text all the time.
Thanks

**Comment by oxydeon** [comment]
if you start typing quickly, before url update, you don't have to select the url ;)  
Can be useful waiting the fix

**Comment by gene-pavlovsky** [comment]
True, this works if you're fast enough. But sometimes I want to ready my fortune first, then go to the page :)

**Comment by oxydeon** [comment]
Chrome 62 is here and solve the issue! :)

**Comment by jimschubert** [comment]
Thanks for reporting back about it. If a few more people say it's fixed, I'll close all the issues.

**Comment by JBtje** [comment]
Just updated to Version 62.0.3202.62 (Official Build) (64-bit) -> Problem is solved.

**Comment by cjauvin** [comment]
Ahhh what a relief!! 😹 
For those like me who couldn't wait for the little green arrow to appear: Help -> About Google Chrome

**Comment by jimschubert** [comment]
Thanks, all! I'll leave it open for a day or two. It's a good point that people may not know how to update.

**Comment by stenrap** [comment]
Fixed in Chrome 62 for me too.

**Comment by gene-pavlovsky** [comment]
Fixed for me as well. One thing to note, maybe I just have too many tabs open, but it takes 2-3 seconds to load the new tab content (which is a small local file:/// page)
