### ISSUE TITLE
not compatible with duplicate tabs remover

### ISSUE THREAD

**Issue by godswift** [jimschubert/NewTab-Redirect#156]
https://chrome.google.com/webstore/detail/duplicate-tab-helper/oaceoebbkmkgfjhmngdinoclnionlgoh

Persists on creating a new tab, instead of closing duplicates, non-recognizant

**Comment by jimschubert** [comment]
I don't think this would be an issue with New Tab Redirect as the default behavior is to update the new tab using built-in Chrome APIs. There's literally nothing I can change about how my extension works to fix that other extension's behavior.
