### ISSUE TITLE
Focus Not Given To Page When Using Local File As URL

### ISSUE THREAD

**Issue by MichaelFoss** [jimschubert/NewTab-Redirect#165]
Using 74.0.3729.157 (Official Build) (64-bit) on Windows 10 version 1809 (OS Build 17763.503). Both have all updates installed.

When using a URL beginning with "http" (e.g. `http://www.google.com/`), the extension does _not_ automatically highlight the Omnibox. However, when the URL begins with "file" (e.g. `file:///C:/Home/index.html`), the Omnibox is _always_ highlighted and focused.

Is there a way to have the browser treat local URLs similar to remote URLs? Or is this a browser feature that is outside of the control of the extension code (see extension author's possibly related comment [here](https://github.com/jimschubert/NewTab-Redirect/issues/46#issuecomment-38577736)).

**Comment by thefiercekid** [comment]
Was just about to talk about this. Yeah, it's kind of an eyesore. Please clear the Omnibox when we use a file.

**Comment by Lunchb0ne** [comment]
Yea, I have the same problem. It would be nice to do this without using a localwebserver.

**Comment by jimschubert** [comment]
This is a limitation of the browser and is documented at https://github.com/jimschubert/NewTab-Redirect/blob/master/README.md#omnibar-support
