### ISSUE TITLE
URL bar not auto selected on new tab

### ISSUE THREAD

**Issue by Cmarullo308** [jimschubert/NewTab-Redirect#179]
When I open a new tab, it used to always have the URL/Search bar selected by default and since the last chrome or windows update (Not sure) it no longer selects the URL bar by default which is pretty annoying

**Comment by biomadeira** [comment]
Same for me! Thanks

**Comment by Restex** [comment]
Same for me. I think its since the last Chrome update.

**Comment by Jaminator827** [comment]
Same for me, happened after I restarted my computer

**Comment by morene338sandro** [comment]
Short term solution is just to remove the addres you redirect to. Then the Searchbar is auto selcted.

**Comment by smuckle** [comment]
Another workaround is to use ctrl-L to highlight the URL bar (found that out by reading this project's wiki). Still, I hope this is fixable, it smooths out a sequence I do at least 100 times a day.

**Comment by DeVilAus** [comment]
+1 same issue. Definitely seems to be after a recent Chrome update. Thanks for the tip @smuckle!

**Comment by ddBenny** [comment]
+1 please fix :)

**Comment by benmadethis** [comment]
Same here, but on MacOS. Must be the recent Chrome update.

**Comment by markwu** [comment]
Same here on macOS.

**Comment by jimschubert** [comment]
Folks, this is explained in the README that extensions have no control over the omnibar.

https://github.com/jimschubert/NewTab-Redirect/blob/master/README.md#omnibar-support

**Comment by Restex** [comment]
This is awkward - memo to self: RTFM ;)

**Comment by cg089** [comment]
I think it used to work until the last couple of days. I catch myself now often open  a new tab, start typing until I realize my typings went into /dev/null

**Comment by jimschubert** [comment]
See also #174

**Comment by bbodenmiller** [comment]
Here's a workaround: https://github.com/jimschubert/NewTab-Redirect/issues/174#issuecomment-634300102

**Comment by jimschubert** [comment]
That linked comment is not a "workaround", it's directing people to install another extension which gives the developer access to all sites you visit. I pride myself on never selling this extension, never collecting user data, and protecting my users who are quite often non-technical. So I'm losing this issue to try and prevent others from being directed to this "workaround".

A better workaround for technical folks is to create the two files you need for a minimal new tab override page and not be beholden to developers who generally don't consider your online safety as a priority

**Comment by bbodenmiller** [comment]
> A better workaround for technical folks is to create the two files you need for a minimal new tab override page and not be beholden to developers who generally don't consider your online safety as a priority.

@jimschubert is there more details on how to setup this temporary workaround?
