### ISSUE TITLE
Cannot set New Tab page to the speed dial page of another extension

### ISSUE THREAD

**Issue by Dudeguy409** [jimschubert/NewTab-Redirect#183]
Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

I installed this extension (NewTab-Redirect) so that I could set my new tab page to my speed dial page:  https://chrome.google.com/webstore/detail/speed-dial/iabdallljpblefakghecaimjnfgcmmdg?hl=en

However, when I try this, I get the following error page:

Requests to the server have been blocked by an extension.
Try disabling your extensions.
ERR_BLOCKED_BY_CLIENT

If I hit ctrl+r or hit the reload button, the page fails to reload, but if I highlight the browser bar and hit enter, the navigation is successful.  I'm pretty sure that the issue is that Chrome doesn't allow one extension to navigate to a different extension (even in a new tab), but figured I'd ask to be sure.  Didn't see any similar issues posted.

**Comment by Dudeguy409** [comment]
Yeah, I tried this out with a second extension and it doesn't work either.  In the readme, NewTab Redirect claims that it allows new tab pages to be set to extension pages, but that doesn't seem to be the case.  Not any longer, anyways.

**Comment by jimschubert** [comment]
@Dudeguy409 thanks for the report. Unfortunately, this has never been supported. The "Extensions" in the readme refers to `chrome://extensions`, which is an option on the Options page of New Tab Redirect.
