### ISSUE TITLE
New Tab Redirect affects behavior of Bookmark Bar visibility

### ISSUE THREAD

**Issue by ahmogit** [jimschubert/NewTab-Redirect#186]
### Summary
With NTR extension disabled, opening a new tab always results in the Bookmark Bar becoming visible on the new page, regardless of whether it had been visble or hidden on the originating page. (TTBOMR, this has been native Linux-Chromium behavior for several years.)

With NTR enabled, opening a new tab seems to just duplicate the state of the Bookmark Bar from the originating page: If the Bookmark Bar was visble on the originating page, then it is also visible on the new page that appears when NTR is invoked. If the Bookmark Bar was hidden on the originating page, then it remains hidden on the newly opened tab page.

### Steps to reproduce

With NTR enabled:

1. Open arbitrary URL
2. If Bookmark Bar is visible, type ctrl-shft-B to hide it.
3. Type ctrl-T to invoke NTR and bring up new tab page
4. Observe new tab page does not show Bookmark Bar.

With NTR disabled, steps are the same as above, except observation (4) is that the Bookmark Bar is always shown.

### Comments
The native behavior fits well with my typical workflow, because  with high probability, opening a new tab is almost always followed by opening a bookmark from the Bookmark Bar. Although ctrl-shft-B can be used to force the Bookmark Bar to appear, it's extra keystrokes that I'd prefer to avoid.

I did research this for an hour or so before reporting it here, looking thru the github issues and googling at large  but was surprised not to find any similar reports This usually means that the problem is on my end, perhaps some pecularity in my setup, or an error or misunderstanding on my part in the Chromium version/options, or NTR options, or how they may interact. 

So the first question is simply: Can anyone reproduce this?

Second: If it is reproducible and acknowledged to be a behavior change due to NTR, can an option possibly be implemented to allow choosing between native and "clone Bookmark Bar" behavior?

Thanks!

### Version info
  * O/S: Arch Linux, x86_64
  * Ungoogled Chromium, 84.0.4147.105, from Arch Linux repo.
  * New Tab Redrect V3.1.5, installed from CRX file downloaded from WebStore.
  * NTR options and permissions page screenshots attached. (NOTE: Toggling
    the "management" permission to "approve" has no effect on the issue.)
![ntr_screenshots](https://user-images.githubusercontent.com/5025879/93635110-f8156980-f9ae-11ea-92d6-bfdf627f8c75.gif)

**Comment by jimschubert** [comment]
@ahmogit the bookmark bar you're seeing when NTR is disable is a bookmark bar built into the default new tab page and not the "real" bookmarks bar. This isn't an issue with NTR. It is expected behavior in Chrome that the bookmark bar stays hidden when you open a new tab while hidden, and stays visible when you open a new tab while visible.

**Comment by ahmogit** [comment]
Hi Jim, thanks for your response. But I'm not sure I understand it. Can you explain a little further?

Here's what I don't get:

You say that there is a bookmark bar that is "built in" to the default new-tab page, and you talk about it as though it is distinct from the "real" bookmark bar.  But when NTR is disabled, the bookmark bar that appears when a new tab is opened is identical in all visible respects to the current state of the "real" bookmark bar (i.e. as customized and maintained by me via the Bookmark Manager). So I don't understand why you're referring to that as "built in". That phrase usuallly means something  roughly synonymous with "default" or "standard". But what actually appears is not some sort of default or standarized bookmark bar; it is identical to the current state of my "bookmark bar" folder as displayed in the Bookmark Manager.

 I just checked this again now, to be sure I'm not mis-reporting the default (non-NTR) behavior.  It does appear to be correct as stated above (and in the original ticket post).

Also, in the last sentence of your response, you say:

`It is expected behavior in Chrome that the bookmark bar stays hidden when you open a new tab while hidden, and stays visible when you open a new tab while visible.`

But with NTR disabled, that is **not** what is observed. What is observed is that "the" bookmark bar becomes visible, regardless of its visibility state on the originating page. That is the behavior that I am requesting to be implemented in NTR, if possible.

Sorry if I'm being obtuse on all this, I'm not trying to give you a hard time. Just want to understand more clearly what is going on.

Thanks!
