### ISSUE TITLE
Option of multiple URLs that NewTab redirects to in rotating order

### ISSUE THREAD

**Issue by theccft** [jimschubert/NewTab-Redirect#190]
Please

**Comment by jimschubert** [comment]
This is not something I'm able to add, as it would add too long to the loading time and cause issues for everyone. Sorry.

**Comment by jimschubert** [comment]
I'm sure there are other extensions that do what you're looking for. If not, you could maybe modify an example I created which does something similar: https://github.com/jimschubert/chrome-random-newtab
