### ISSUE TITLE
Too many risks and vulnerabilities

### ISSUE THREAD

**Issue by dllu** [jimschubert/NewTab-Redirect#204]
This extension is too bloated, requiring excessive permissions. There is no need to have either Angular or JQuery in this extension!

https://crxcavator.io/report/icpgjfneehieebagbmdbhnlpiopdcmna?platform=Chrome&new_scan=true

**Comment by jimschubert** [comment]
Chrome extensions are sandboxed. The app only requires minimal permissions and others are opt-in.
