### ISSUE TITLE
Chrome blocks extension pages

### ISSUE THREAD

**Issue by DovieW** [jimschubert/NewTab-Redirect#205]
I'm trying to open a chrome extension page on new tab. But I get:
"
This page has been blocked by chrome
ERR_BLOCKED_BY_CLIENT
"
I have to reload the page.
The extension is [TabXpert](https://chrome.google.com/webstore/detail/jmeokbeppmkkdkhkffihoblceecdapeh)

**Comment by jimschubert** [comment]
I don't maintain TabXpert. Open an issue on the appropriate extension.
