### ISSUE TITLE
Option to keep focus on browser address bar

### ISSUE THREAD

**Issue by Serhioromano** [jimschubert/NewTab-Redirect#215]
When new tab is opened usually cursor focus is on address bar. I use this extension to redirect to my selfhosted dashboard app. That all works fine. But after redirect I would like to keep focus on address bar. If I want I use dashboard icons to navigate but if not I continue my usual routine to type and search recent pages or search suggestions.

**Comment by jimschubert** [comment]
This is not functionality which can be handled via extensions. See https://github.com/jimschubert/NewTab-Redirect#omnibar-support
