### ISSUE TITLE
Web page bet365.com won't load

### ISSUE THREAD

**Issue by Damrak1** [jimschubert/NewTab-Redirect#217]
I can't load the web page **bet365.com** when this extension is switched on. When I turn it off, I can. 
I found a workaround: loading the page from a text file, but I would like to go to it directly from the address bar in chrome or from a bookmark.

**Comment by jimschubert** [comment]
This extension has no impact on loading web pages. I would recommend you don't go to that site or uninstall this extension.

**Comment by Damrak1** [comment]
Yes, unfortunately it did. But that was three months ago, in the mean time it has been fixed.
