### ISSUE TITLE
Local file doesen't work

### ISSUE THREAD

**Issue by thepepp** [jimschubert/NewTab-Redirect#219]
After the latest windows update, NTR does not work on a local file. I set D:\home.htm or file:///D:/Homepage/home.htm and it no longer works. it works with pages on the web like wikipedia.com and chrome://apps . All permissions are granted.

**Comment by kendo458** [comment]
Same here. Unable to load local files. Just a blank screen with "New Tab Redriect chrome://newtab"  on the tab title
Chrome Version 118.0.5993.71 (Official Build) (64-bit)

**Comment by kendo458** [comment]
oh I just saw the comment below this one titled:
Chrome Beta 118 restricted access to a local file in "New Tab Redirect"
It has info on how to resolve

**Comment by andrewliles** [comment]
See #218
