### ISSUE TITLE
Local file is working on chromium based browsers but not on google chrome itself 

### ISSUE THREAD

**Issue by bilalazhar72** [jimschubert/NewTab-Redirect#222]
i recently tried the extension on thorium browser which is open source , and the extension works fine for redirecting the local file 
**Here is the sample screenshot to show that its working ** 

![image](https://github.com/jimschubert/NewTab-Redirect/assets/108006611/318fc563-3ff1-4fc3-aad2-562ae2759181)

If the engine is fine there should be a way for it to work with chrome as well i think this happened after new chrome update . i hope this can help devs and if some one else is looking into it to fix this thanks

**Comment by hgoodman-ata** [comment]
Local file access no longer works in Chromium or Brave

**Comment by Vasqs** [comment]
Enable "Allow access to file URLs" on extension details
![Screenshot_20231115_201831-1](https://github.com/jimschubert/NewTab-Redirect/assets/17505584/3dc1985b-8277-4f74-ae3d-50b350fd4090)

**Comment by hgoodman-ata** [comment]
Woohoo!  Really appreciate this, did't realize how central this is to my workflow and I just sent you a donation.

Because it took me a few minutes to find the setting, its in:

menu -> extentsions -> manage extenstions: new tab redirect DETAILS button then the "Allow access to file URLs"

**Comment by jimschubert** [comment]
Thanks for answering, folks. As part of #218 which required updating the extension to use manifest v3 (they don't allow publishing with v2 anyone) and new changes to chrome, this is an unfortunate side effect.
