### ISSUE TITLE
Local files not working

### ISSUE THREAD

**Issue by poparad** [jimschubert/NewTab-Redirect#225]
About a month ago the extension broke after a Chrome update and no longer works with local files, either by redirect or refresh. I'm on the current build of Chrome (Version 119.0.6045.160 (Official Build) (64-bit)).

**Comment by Flapperke** [comment]
Same over here. Local files link end up with a blank page.

**Comment by jimschubert** [comment]
Chrome added a new option which you have to manually select to add access to file URLs. Go to chrome://extensions and you'll see the toggle.

**Comment by Flapperke** [comment]
Hi there,I saw that info on the web, went looking, but couldn't find that toggle...I'll give it a second try though...ThanksHugoSent from Android deviceOn 01 Dec 2023 03:28, Jim Schubert ***@***.***> wrote:
Chrome added a new option which you have to manually select to add access to file URLs. Go to chrome://extensions and you'll see the toggle.

**Comment by poparad** [comment]
Thanks! That fixed it! Maybe a sentence could be added to the settings page for this extension mentioning which option needs to be enabled for it to work and where to find it. The settings page is the first place I went to try to fix the problem so seeing it there would've led me directly to what I needed to do.

**Comment by RHeynsZa** [comment]
You're looking for 
> Allow access to file URLs
![image](https://github.com/jimschubert/NewTab-Redirect/assets/58415372/505589b9-61fe-413c-ac5f-6cd3ef50ed24)

**Comment by Flapperke** [comment]
Thanks Ruan👍🤗Sent from Android deviceOn 05 Dec 2023 11:42, Ruan Heyns ***@***.***> wrote:
You're looking for

Allow access to file URLs
image.png (view on web)

**Comment by Flapperke** [comment]
OK , found the new option both in Edge and in Brave.
Both work again as I'm used to.
Thanks !
Hugo

**Comment by jimschubert** [comment]
I've added to the readme: https://github.com/jimschubert/NewTab-Redirect/blob/master/README.md#missing-local-files

**Comment by Flapperke** [comment]
Thanks Jim👍Sent from Android deviceOn 10 Dec 2023 17:38, Jim Schubert ***@***.***> wrote:
Closed #225 as completed.
