### ISSUE TITLE
Bug: Redirect always focus URL bar when using "file:///"

### ISSUE THREAD

**Issue by alejgr** [jimschubert/NewTab-Redirect#231]
Hi, first off, thanks for this amazing extension. Its a must for me :)

I've transitioned from using a public website to a static, local startpage, and now I'm encountering some issues with the navigation bar focus. In redirect.js, we have this condition:

```js
if (/^http[s]?:/i.test(url) && items["always-tab-update"] !== true) {
    document.location.href = url;
} else {
    chrome.tabs.getCurrent(function (tab) {
      // etc
}
```

The second branch is always triggered because the file:/// protocol does not match the regex, which results in ignoring the `always-tab-update=false` option.

For now, I've just forked the extension and removed this regex condition. I'm not sure why the tab is always updated for an http/https URL, so I don't feel confident that my solution is good enough to open a PR 😛 

Any ideas? Thanks!

**Comment by garrison** [comment]
See https://github.com/jimschubert/NewTab-Redirect/wiki#page-focus-on-file-redirects for potentially some related info.

In any case, here is the same code snippet, except linked to its full context:

https://github.com/jimschubert/NewTab-Redirect/blob/422858b1b728c14e892f69faa7ba1dd76c74d1ad/js/redirect.js#L9-L12

**Comment by alejgr** [comment]
Thanks!
