### ISSUE TITLE
highlight omnibar upon new tab

### ISSUE THREAD

**Issue by bleeper4** [jimschubert/NewTab-Redirect#46]
I use this extension only to restore the apps page functionality when I open a new tab. It used to be that upon opening a new tab, the address bar would be highlighted, so that I could still type a search into the address bar. With a recent update, the bar is no longer highlighted, and instead the cursor is put at the end of "chrome://apps/". It's annoying because I have to then highlight the "chrome://apps/" (or hit ctrl+A) and replace it with my search to search anything.
I am on Chrome 34.0.1847.76 beta-m.

**Comment by Cole128** [comment]
This is happening to me, but it was more annoying, because it didn't happen before. It seems like this has always been an issue for everyone else, but for me it used to select all the text and now it doesn't.
