### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by crunchiness** [jimschubert/NewTab-Redirect#90]
http://pbrd.co/13Efz6R
a bit of Yahoo icon visible just before "Chrome Pages" (my screen resolution is 1366x768)
gives an illusion that there are more icons under "Chrome Pages"

![image](https://cloud.githubusercontent.com/assets/109659/5563840/38055756-8e4b-11e4-8c18-3cfa8fd92728.png)

**Comment by jimschubert** [comment]
Any news on this? I'm thinking it's screen/monitor artifacting or any slew of things that could influence the rendering of the browser. In any case, that's not something I have control over.

**Comment by jimschubert** [comment]
Closing as not reproducible.
