### ISSUE TITLE
chrome://extensions allows linking to a specific ID

### ISSUE THREAD

**Issue by Walkman100** [jimschubert/NewTab-Redirect#94]
I've recently found that you can make a URL for the chrome://extensions page that will scroll down to & highlight the linked ID, e.g. `chrome://extensions/?id=icpgjfneehieebagbmdbhnlpiopdcmna`

Aulthough you might already know this, I thought you should update [this wiki section](https://github.com/jimschubert/NewTab-Redirect/wiki#how-do-i-remove-this-extension-) and similar with a link like that instead of telling users to go to chrome://extensions and find NTR. I would've updated it myself, but it appears you have the `Restrict editing to collaborators only` option on.

(Sorry for making an issue - GitHub doesn't really have a better way of sending messages)

**Comment by jimschubert** [comment]
No problem, that's what the issues section is for. It's a great suggestion and I've updated the wiki.

If you want to contribute code or documentation and become a collaborator, you can email me (email is on my profile) and we could discuss.
