### ISSUE TITLE
question about permissions

### ISSUE THREAD

**Issue by ilanle** [jimschubert/NewTab-Redirect#96]
Hi,
I went ahead and installed the extension , and set the page I want to redirect to from the setting, and that worked fine.
Later I found that I was asked for a significant permission to manipulate extensions. What is this permission needed for?

**Comment by jimschubert** [comment]
Permissions are explained [on the wiki](https://github.com/jimschubert/NewTab-Redirect/wiki/Permissions) as well as on the extension's options page.

If you're redirecting to a page, you don't need any of the additional permissions necessary for the built in new tab replacement. Those permissions only apply if you're not using a custom redirect page and are using my version of the apps page instead.

**Comment by ilanle** [comment]
Right.
Thank you
